config/routes.rb
Mundodastrevas::Application.routes.draw do
  resource :search, only: [:show]
  resources :pages, only: [:show]

  root 'home#index'

  resources :zines, only: [:index, :show] do
    resources :posts, only: [:show]
  end

  resources :forums, only: [:show, :index] do
    resources :topics, only: [:show]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.erb
<% content_for :page_description, 'Notícias, análises, eventos, fóruns, resenhas,
  crônicas e materiais independentes de Vampiro: o Réquiem, Mago: o Despertar,
  Lobisomem: os Destituídos, Changeling: os Perdidos, Promethean: the Created e
  demais jogos do Mundo das Trevas - World of Darkness Storytelling RPG.' %>
<% content_for :page_keywords, 'Mundo das Trevas, World of Darkness, Vampiro,
  Vampire, Requiem, Mago, Mage, Despertar, Awakening, Lobisomem, Werewolf, Destituidos,
  Forsaken, Changeling, Perdidos, Lost, Promethean, Created, Geist, Sin Eaters, Hunter,
  Vigil, Mummy, Curse, Demon, Descent, Storytelling, RPG' %>
<% content_for :page_type, 'website' %>
<% content_for :canonical_url, root_url %>

<% content_for :layout_top  do %>
  <div class="page-top">
    <div class="container">
      <h1><%= link_to 'Mundo das Trevas', root_path %></h1>
      <p class="lead hidden-sm-down">A comunidade brasileira de storytelling</p>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col">
    <%= link_to 'Zines', zines_path, class: 'btn btn-primary btn-lg btn-block' %>
  </div>

  <div class="col">
    <%= link_to 'Fóruns', forums_path, class: 'btn btn-primary btn-lg btn-block' %>
  </div>
</div>