config/routes.rb
Mundodastrevas::Application.routes.draw do
  resource :search, only: [:show]
  resources :pages, only: [:show]

  root 'home#index'

  resources :zines, only: [:index, :show] do
    resources :posts, only: [:show]
  end

  resources :forums, only: [:show, :index] do
    resources :topics, only: [:show]
  end
end

app/models/zine.rb
class Zine < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 66_000 }
  validates :user_id, presence: true
  validates :slug,
            presence: true,
            uniqueness: {
              case_sensitive: false
            },
            format: { with: /\A(([a-z]|[A-Z]|[0-9]|-)+)\z/ },
            length: { maximum: 100, minimum: 3 }

  mount_uploader :image, ImageUploader

  def to_param
    slug
  end

  def to_s
    name
  end
end

app/controllers/zines_controller.rb
class ZinesController < ApplicationController
  def index
    @zines = Zine.all.includes(:posts, :user).order(:name)
  end

  def show
    @zine = Zine.find_by!(slug: params[:id])
    @posts = @zine.posts.order(created_at: :desc)
  end
end

app/views/zines/index.html.erb
<% content_for :page_title, t('.title') %>
<% content_for :page_canonical_url, zines_url %>

<h1><%= t '.title' %></h1>

<div class="list-group">
  <% @zines.each do |zine| %>
    <%= link_to zine, class: 'list-group-item list-group-item-action flex-column align-items-start' do %>
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= zine %></h5>
        <small><%= pluralize zine.posts.count, 'post', plural: 'posts' %></small>
      </div>
      <p class="mb-1">Por <%= zine.user %></p>
    <% end %>
  <% end %>
</div>

app/views/zines/show.html.erb
<% content_for :page_title, @zine %>
<% content_for :page_author, @zine.user %>
<% content_for :page_description, truncate_rich(@zine.description) %>
<% content_for :page_canonical_url, zine_url(@zine) %>
<% content_for :page_image, URI(root_url) + @zine.image.url %>
<% content_for :page_updated_at, @zine.updated_at %>

<h1><%= @zine %></h1>

<div class="row">
  <div class="col-md-8">
    <% if @zine.image.file.present? %>
      <%= image_tag @zine.image.url, class: 'zine-image img-fluid' %>
    <% end %>

    <div class="zine-description"><%= sanitize @zine.description %></div>

    <h2><%= t '.posts', zine: @zine %></h2>

    <% @posts.each do |post| %>
      <div class="list-item-with-image post-list-item">
        <%= link_to [post.zine, post] do %>
          <%= image_tag post.image.small.url %>
        <% end %>

        <h4><%= link_to post, [post.zine, post] %></h4>

        <p>
          <%= truncate_rich(post.content) do %>
            <%= link_to t('.more'), [post.zine, post] %>
          <% end %>
        </p>
      </div>
    <% end %>

    <% if @posts.empty? %>
      <div class="alert alert-info"><%= t '.empty' %></div>
    <% end %>
  </div>

  <div class="col-md-4">
    <div class="card zine-author">
      <div class="card-header"><%= t '.author' %></div>

      <div class="card-block">
        <%= image_tag @zine.user.avatar.small.url, class: 'rounded-circle img-thumbnail img-fluid' %>
        <h3 class="card-title"><%= @zine.user %></h3>
        <p class="card-text bio"><%= truncate_rich @zine.user.bio %></p>
      </div>
    </div>
  </div>
</div>