config/routes.rb
Mundodastrevas::Application.routes.draw do
  resource :search, only: [:show]
  resources :pages, only: [:show]

  root 'home#index'

  resources :zines, only: [:index, :show] do
    resources :posts, only: [:show]
  end

  resources :forums, only: [:show, :index] do
    resources :topics, only: [:show]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :zine
  belongs_to :user

  validates :name, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 66_000 }
  validates :zine_id, presence: true
  validates :slug,
            presence: true,
            uniqueness: {
              case_sensitive: false
            },
            format: { with: /\A(([a-z]|[A-Z]|[0-9]|-)+)\z/ },
            length: { maximum: 100, minimum: 3 }
  validates :user_id, presence: true

  mount_uploader :image, ImageUploader

  after_create :touch_zine

  def to_param
    slug
  end

  def to_s
    name
  end

  protected

  def touch_zine
    zine.try(:touch, :last_post_at)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @zine = Zine.find_by!(slug: params[:zine_id])
    @post = @zine.posts.find_by!(slug: params[:id])
  end
end

app/views/posts/show.html.erb
<% content_for :page_title, @post %>
<% content_for :page_author, @post.user %>
<% content_for :page_description, truncate_rich(@post.content) %>
<% content_for :page_canonical_url, zine_post_url(@zine, @post) %>
<% content_for :page_image, URI(root_url) + @post.image.url %>
<% content_for :page_updated_at, @post.updated_at %>
<% content_for :page_see_also, zine_url(@zine) %>

<% content_for :layout_top do %>
  <div class="post-top"
    <% if @zine.image.file %>
      style="background-image: url(<%= @zine.image.url %>)"
    <% elsif @post.image.file %>
      style="background-image: url(<%= @post.image.url %>)"
    <% end %>
  >
  </div>
<% end %>

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-9 offset-md-1">
    <div class="post">
      <h1><%= @post %></h1>

      <p class="author-and-date">
        <%= t '.author_and_date.html',
          user: @post.user,
          date: time_tag(@post.created_at.to_date, format: :long) %>
      </p>

      <%= image_tag @post.image.url, class: 'zine-image img-fluid' if @post.image.file.present? %>

      <div class="content"><%= sanitize @post.content %></div>

      <div class="card zine-link">
        <div class="card-block">
          <p><%= link_to @zine, @zine, title: t('.index') %></p>

          <div class="btn-group" role="group">
            <% if previous_post = @zine.posts.where('created_at < ?', @post.created_at).order(created_at: :desc).first %>
              <%= link_to zine_post_path(@zine, previous_post), class: 'btn btn-secondary', title: previous_post do %>
                &larr; <%= t '.previous' %>
              <% end %>
            <% else %>
              <button type="button" class="btn btn-secondary" disabled>
                &larr; <%= t '.previous' %>
              </button>
            <% end %>

            <%= link_to t('.index'), @zine, title: @zine, class: 'btn btn-secondary' %>

            <% if next_post = @zine.posts.where('created_at > ?', @post.created_at).order(created_at: :asc).first %>
              <%= link_to [@zine, next_post], class: 'btn btn-secondary', title: next_post do %>
                <%= t '.next' %> &rarr;
              <% end %>
            <% else %>
              <button type="button" class="btn btn-secondary" disabled>
                <%= t '.next' %> &rarr;
              </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div id="disqus_thread"></div>
    <script>
      /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
      /*
      var disqus_config = function () {
      this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
      //this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
      };
      */
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://mundodastrevas.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>
</div>